config/routes.rb
OmniSearch::Application.routes.draw do
  resources :revisions do
    resources :search_engines

  end

  match 'revisions/:id/checkupdates' => 'revisions#checkUpdates', :as => :checkUpdates
  match 'revisions/:id/getupdates' => 'revisions#getUpdates', :as => :getUpdates
  root :to => 'revisions#index'

end

app/models/revision.rb
class Revision < ActiveRecord::Base
  attr_accessible :nbItem, :published
  has_many :search_engines
  before_create :initNbItem

  def initNbItem
    self.nbItem = 0
  end

end

app/models/search_engine.rb
class SearchEngine < ActiveRecord::Base
  attr_accessible :country, :name, :revision_id, :url, :icon, :remote_icon_url
  belongs_to :revision
  mount_uploader :icon, IconUploader

  after_create :updateRevision

  def updateRevision
    r = Revision.find(self.revision_id)
    r.nbItem = r.nbItem+1
    r.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/revisions_controller.rb
class RevisionsController < ApplicationController
  # GET /revisions
  # GET /revisions.json
  def index
    @revisions = Revision.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @revisions }
    end
  end

  # GET /revisions/1
  # GET /revisions/1.json
  def show
    @revision = Revision.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @revision }
    end
  end

  # GET /revisions/new
  # GET /revisions/new.json
  def new
    @revision = Revision.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @revision }
    end
  end

  # GET /revisions/1/edit
  def edit
    @revision = Revision.find(params[:id])
  end

  # POST /revisions
  # POST /revisions.json
  def create
    @revision = Revision.new(params[:revision])

    respond_to do |format|
      if @revision.save
        format.html { redirect_to @revision, notice: 'Revision was successfully created.' }
        format.json { render json: @revision, status: :created, location: @revision }
      else
        format.html { render action: "new" }
        format.json { render json: @revision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /revisions/1
  # PUT /revisions/1.json
  def update
    @revision = Revision.find(params[:id])

    respond_to do |format|
      if @revision.update_attributes(params[:revision])
        format.html { redirect_to @revision, notice: 'Revision was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @revision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /revisions/1
  # DELETE /revisions/1.json
  def destroy
    @revision = Revision.find(params[:id])
    @revision.destroy

    respond_to do |format|
      format.html { redirect_to revisions_url }
      format.json { head :no_content }
    end
  end

  def getUpdates

    @revisions = Revision.where("id > ? and published='1'", params[:id])

    respond_to do |format|
      if @revisions.count > 0
        format.json
        #format.json { render json: s }
      else
        format.json { head :no_content }
      end
    end
  end

  def checkUpdates
    @revisions_count = Revision.where("id > ? and published='1'", params[:id]).count
    respond_to do |format|
      format.json
    end
  end


end

app/controllers/search_engines_controller.rb
class SearchEnginesController < ApplicationController
  # GET /search_engines
  # GET /search_engines.json
  def index
    @search_engines = SearchEngine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @search_engines }
    end
  end

  # GET /search_engines/1
  # GET /search_engines/1.json
  def show
    @search_engine = SearchEngine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search_engine }
    end
  end

  # GET /search_engines/new
  # GET /search_engines/new.json
  def new
    @revision = Revision.find(params[:revision_id])
    @search_engine = @revision.search_engines.new

    respond_to do |format|
      format.html
    end
  end

  # GET /search_engines/1/edit
  def edit
    @search_engine = SearchEngine.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  # POST /search_engines
  # POST /search_engines.json
  def create
    @revision = Revision.find(params[:revision_id])
    @search_engine = @revision.search_engines.new(params[:search_engine])
    #@search_engine.icon = params[:search_engine][:icon]

    respond_to do |format|
      if @search_engine.save
        format.html { render 'revisions/show' , notice: 'Search engine was successfully created.' }
      else
        format.html { render action: "new" }
        format.json { render json: @search_engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /search_engines/1
  # PUT /search_engines/1.json
  def update
    @search_engine = SearchEngine.find(params[:id])

    respond_to do |format|
      if @search_engine.update_attributes(params[:search_engine])
        format.html { redirect_to @search_engine, notice: 'Search engine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @search_engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search_engines/1
  # DELETE /search_engines/1.json
  def destroy
    @revision = Revision.find(params[:revision_id])
    @search_engine = SearchEngine.find(params[:id])
    @search_engine.destroy

    respond_to do |format|
      format.js { render action: "index" , notice: 'Search engine was successfully created.' }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/revisions_helper.rb
module RevisionsHelper
end

app/helpers/search_engines_helper.rb
module SearchEnginesHelper

  def full_icon(path)
    request.protocol+request.host_with_port+path.to_s
  end

end

app/views/layouts/application.html.haml
%html
  %head
    %title OmniSearch Admin
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.brand{:href => "#"} OmniSearchAdmin

    .container
      - flash.each do |name, msg|
        %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
          %a.close{"data-dismiss" => "alert"} x
          = msg
      = yield
    = yield :scripts
    #myModal.modal.hide.fade.in
    #myModalLarge.modal-large.hide.fade.in

app/views/revisions/_form.html.haml
= form_for @revision do |f|
  - if @revision.errors.any?
    #error_explanation
      %h2= "#{pluralize(@revision.errors.count, "error")} prohibited this revision from being saved:"
      %ul
        - @revision.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :published
    = f.check_box :published
  .actions
    = f.submit 'Save'

app/views/revisions/edit.html.haml
%h1 Editing revision

= render 'form'

= link_to 'Show', @revision
\|
= link_to 'Back', revisions_path

app/views/revisions/index.html.haml
%h1 Listing revisions

%table
  %tr
    %th Nbitem
    %th Published
    %th
    %th
    %th

  - @revisions.each do |revision|
    %tr
      %td= revision.nbItem
      %td= revision.published
      %td= link_to 'Show', revision
      %td= link_to 'Edit', edit_revision_path(revision)
      %td= link_to 'Destroy', revision, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Revision', new_revision_path

app/views/revisions/new.html.haml
%h1 New revision

= render 'form'

= link_to 'Back', revisions_path

app/views/revisions/show.html.haml
%p#notice= notice

%p
  %b Nbitem:
  = @revision.nbItem
%p
  %b Published:
  = @revision.published

= link_to new_revision_search_engine_path(@revision), :class => 'btn btn-info' do
  %i.icon-file.icon-white
  Ajouter un site

%br
%br

#dvSeList.well
  - if @revision.search_engines.all.count > 0
    = render 'search_engines/index'
  - else
    %p
      Aucun site enregistre pour l'instant

= link_to 'Edit', edit_revision_path(@revision)
\|
= link_to 'Back', revisions_path

app/views/search_engines/_edit.html.haml
= form_for @search_engine, :remote => true, :method => :post  do |f|
  = render 'form', :f => f

app/views/search_engines/_form.html.haml
.control-group
  = f.label :name, :class => 'control-label'
  .controls
    = f.text_field :name
.control-group
  = f.label :url, :class => 'control-label'
  .controls
    = f.text_field :url, :class => 'input-url'
.control-group
  = f.label :country, :class => 'control-label'
  .controls
    = f.text_field :country
.control-group
  = f.label :icon, :class => 'control-label'
  .controls
    = f.file_field :icon, :class => 'input-xlarge'

.control-group
  = f.label :icon, :class => 'control-label'
  .controls
    = f.text_field :remote_icon_url, :class => 'input-xlarge'

= f.hidden_field :revision_id

app/views/search_engines/_index.html.haml
%table.table
  %thead
    %tr
      %th Name
      %th Url
      %th Country
      %th Icon
      %th
  - @revision.search_engines.all.each do |search_engine|
    %tbody
      %tr
        %td= search_engine.name
        %td= search_engine.url
        %td= search_engine.country
        %td= image_tag search_engine.icon_url(:ldpi)
        %td
          = link_to revision_search_engine_path(@revision, search_engine), method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'btn btn-mini btn-danger' do
            %i.icon-white.icon-remove
            Supprimer

app/views/search_engines/index.js.erb
$('#myModal').modal('hide');
$('#dvSeList').html("<%= escape_javascript(render 'index') %>");

app/views/search_engines/new.html.haml
= form_for [@revision, @search_engine], :html => {:class =>'form-horizontal', :multipart => true} do |f|
  .modal-header
    %h3
      Nouveau Site
  .modal-body
    = render 'form', :f => f
  .modal-footer
    = button_tag :class =>'btn btn-primary', :type => 'submit' do
      %i.icon-ok.icon-white
      Enregistrer
    = link_to @revision, :class => 'btn btn-warning' do
      %i.icon-remove.icon-white
      Annuler

app/views/search_engines/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @search_engine.name
%p
  %b Url:
  = @search_engine.url
%p
  %b Country:
  = @search_engine.country
%p
  %b Revision:
  = @search_engine.revision_id

= link_to 'Edit', edit_search_engine_path(@search_engine)
\|
= link_to 'Back', search_engines_path